name: Build and Release

on: workflow_dispatch

jobs:
  dl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update index
      run: sudo apt-get update
    
    - name: Install deps
      run: sudo apt-get install cmake libtool nasm libpng-dev pkg-config build-essential wget -yq --no-install-suggests --no-install-recommends --assume-yes
    
    - name: Download source
      run: wget --no-check-certificate https://github.com/mozilla/mozjpeg/archive/v4.1.5.tar.gz -O mozjpeg-4.1.5.tar.gz
    
    - name: Extract files
      run: tar -xzvf mozjpeg-4.1.5.tar.gz

    - name: Build
      run: cmake mozjpeg-4.1.5 && cmake --build .
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: cjpeg-static
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
